<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
    <testsuite name="force.apex" timestamp="2019-03-08T12:23:11+05:45" hostname="https://ap8.salesforce.com" tests="1" failures="1"  errors="0"  time="0.15">
        <properties>
            <property name="outcome" value="Failed"/>
            <property name="testsRan" value="1"/>
            <property name="passing" value="0"/>
            <property name="failing" value="1"/>
            <property name="skipped" value="0"/>
            <property name="passRate" value="0%"/>
            <property name="failRate" value="100%"/>
            <property name="testStartTime" value="Mar 8, 2019 12:23 PM"/>
            <property name="testExecutionTime" value="0.15 s"/>
            <property name="testTotalTime" value="0.15 s"/>
            <property name="commandTime" value="27.97 s"/>
            <property name="hostname" value="https://ap8.salesforce.com"/>
            <property name="orgId" value="00D0o0000017fTLEAY"/>
            <property name="username" value="pitambar@javra.com"/>
            <property name="testRunId" value="7070o0000BaG3pf"/>
            <property name="userId" value="0050o00000W63OuAAJ"/>
        </properties>
        <testcase name="SendIphone" classname="SendIphoneToMemberTest" time="0.15">
            <failure message="System.ListException: List index out of bounds: 0"><![CDATA[Class.SendIphoneToMemberTest.SendIphone: line 13, column 1]]></failure>
        </testcase>
    </testsuite>
</testsuites>
